
version: "2"
services:
  
  elasticsearch:
    container_name: elasticsearch
    image: docker.io/bitnami/elasticsearch:7
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - "elasticsearch_data:/bitnami/elasticsearch"
    networks:
      - elastic
  
  kibana:
    container_name: kibana
    image: docker.io/bitnami/kibana:7
    ports:
      - "5601:5601"
    volumes:
      - "kibana_data:/bitnami/kibana"
    networks:
      - elastic
    depends_on:
      - elasticsearch
  
  minideb:
    container_name: apm-server
    image: joaoevalente97/elastic-apm:v1
    ports:
      - 8200:8200
    networks:
      - elastic
volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local

networks:
  elastic:
    driver: bridge